name: Github Action DevCloudNinjas Example
on: [push]
jobs: 
    Our-First-GHA:
        runs-on: ubuntu-latest
        steps:
            - name: Information about the GH event
              run: echo "Our job is triggered by ${{ github.event_name }} event."
            - name: Details of the ENV
              run: echo "It uses the ${{ runner.os }} server hosted by github."
            - name: Info about the repo
              run: echo "The repo used is ${{ github.repo }} and the ref of the repo is ${{ github.ref }}"
            - name: Running Git Checkout (hope we remember what this does)
              uses: actions/checkout@v3
            - name: Git repo clone
              run: echo "The repo ${{ github.repo }} has been cloned"
            - name: Running the LS comand to list what is in the repo
              run: ls ${{ github.workspace }} 

